name: Deploy to App Runner - Test Environment

on:
  workflow_call:
    inputs:
      AWS_DEFAULT_REGION:
        required: true
        type: string
      TEST_REGION:
        required: true
        type: string
      SERVICE:
        required: true
        type: string
    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true
      ECR_REGISTRY:
        required: true
      ECR_REPOSITORY:
        required: true
      ROLE_ARN:
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Configure AWS credentials
        id: aws-credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ inputs.AWS_DEFAULT_REGION }}
       
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Deploy to App Runner - Test Environment
        id: deploy-apprunner-test
        uses: awslabs/amazon-app-runner-deploy@main
        with:
          service: ${{ inputs.SERVICE }}
          image: ${{ secrets.ECR_REGISTRY }}/${{ secrets.ECR_REPOSITORY }}:${{ github.sha }}
          access-role-arn: ${{ secrets.ROLE_ARN }}
          region: ${{ inputs.TEST_REGION }} 
          wait-for-service-stability-seconds: 300 # Update with the desired timeout duration